# Site
name: 'Blog'
description: 'UKK DOSM | Sharing Section.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
disqus: 'ukkdosm'
email: 'ukkdosm@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    azmi:
      name:           azmi
      site:           #
      avatar:         /assets/images/azmi-02.jpeg
      bio:            "Real INTEGRITY is doing the right thing as your first priority."
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/azmistats

    fatin:
      name:           fatin
      site:           #
      avatar:         /assets/images/fatin-01.jpeg
      bio:            "Statistician, hijabista, extraordinary passion for everything. There’s always room for a new idea, a new step… a new beginning."
      email:          fatinezzati141@gmail.com
      twitter:        https://twitter.com/ezaRis141
      
    najmi:
      name:           najmi
      site:           #
      avatar:         /assets/images/najmi-05.jpg
      bio:            "Data Scientist, designer, love to explore new ideas and empowering +Emotional Intelligence for better future!"
      email:          anajmiariffin@gmail.com
      twitter:        https://twitter.com/najmi_ariffin

    adib:
      name:           adib
      site:           #
      avatar:         /assets/images/adib-03.jpeg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/adibazrishah
      
    aishah:
      name:           aishah
      site:           #
      avatar:         /assets/images/aishah-04.jpeg
      bio:            "Beauty is the new AIR - Action. Intelligent. Respect.!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/AishahRahman_90
      
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
